[build]
builder = "nixpacks"
buildCommand = "cp .env.example .env && composer install --no-dev --optimize-autoloader && npm install && npm run build"

[deploy]
startCommand = "php artisan key:generate --force && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
