[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev --optimize-autoloader && npm install && npm run build"

[deploy]
startCommand = "php artisan migrate --force && php artisan storage:link && apache2-foreground"
healthcheckPath = "/"
healthcheckTimeout = 100
