services:
    - type: web
      name: drhome
      env: docker
      dockerfilePath: ./Dockerfile
      envVars:
          - key: APP_ENV
            value: production
          - key: APP_DEBUG
            value: false
          - key: APP_KEY
            generateValue: true
          - key: APP_URL
            sync: false
          - key: DB_CONNECTION
            value: sqlite
          - key: CACHE_DRIVER
            value: file
          - key: SESSION_DRIVER
            value: file
          - key: QUEUE_CONNECTION
            value: sync
          - key: LOG_CHANNEL
            value: stderr
          - key: LOG_LEVEL
            value: debug
